site_name: OSG Documentation
site_url: https://opensciencegrid.github.io/security/
repo_url: https://github.com/opensciencegrid/security/
theme: 
  name: readthedocs

extra_css:
  - css/extra.css

pages:
- Home: 'index.md'
- CILogon OSG CA: 'OSGCertificateService.md'
- CILogon OSG CA FAQ: 'CILogonOSGFAQ.md'
- OSG CA Distribution: 'CaDistribution.md'
- Policies & Procedures: 'PoliciesProcedures.md'
- Security in OSG:
  - Security Awareness For The OSG: 'SecurityAwarenessForTheOSG.md'
  - Security User Responsibilities: 'SecurityUserResponsibilities.md'
  - Security Site Responsibilities: 'SecuritySiteResponsibilities.md'
  - Best Practices: 'SecurityBestPractices.md'
  - Security in OSG FAQ: 'OSGFAQ.md'

markdown_extensions:
  - admonition
  - osg_markdown.colors

