site_name: OSG Documentation
site_url: https://opensciencegrid.github.io/security
repo_url: https://github.com/opensciencegrid/security
theme: readthedocs

extra_css:
  - css/extra.css

pages:
- Home: 'index.md'
- Incident Discovery Reporting: 'IncidentDiscoveryReporting.md'
- Goals Purpose: 'GoalsPurpose.md'
- Security & Certification FAQ: 'OSGFAQ.md'
- Policies & Procedures: 'PoliciesProcedures.md'
- Team Members: 'SecurityTeamMembers.md'
- Email Lists: 'EmailLists.md'
- Secure Email: 'SecureEmail.md'
- Security Awareness For The OSG: 'SecurityAwarenessForTheOSG.md'

markdown_extensions:
  - admonition
  - osg_markdown.colors

