site_name: OSG Security
site_url: https://opensciencegrid.org/security/
repo_url: https://github.com/opensciencegrid/security/
theme: 
  name: material
  custom_dir: osgthedocs

pages:
- Home: 'index.md'
- Security Team: 'SecurityTeamMembers.md'
- Security Announcements:
  - Overview: 'OSGSecurityAnnouncements.md'
  - Overview x86 vulnerabilities: 'OSGSecurityAnnouncements-x86.md'
  - Announcement Details:
- CILogon OSG CA:
  - CILogon OSG CA: 'OSGCertificateService.md'
  - Frequently Asked Questions (FAQ): 'CILogonOSGFAQ.md'
- Certificate Authorities (CA) Distribution: 'CaDistribution.md'
- OSG Security Policies & Procedures:
  - Including Let’s Encrypt signing certificate in OSG CA bundle: 'LetsEncryptOSGCAbundle.md'
  - Approved OSG Security Policies: 'OSGSecurityPolicies.md'
  - Site/VO Removal Policy: 'SiteVORemovalPolicy.md'
  - OSG Security Procedures: 'OSGSecurityProcedures.md'
  - Site/VO Removal Procedure: 'SiteVORemovalProcedure.md'
  - Secure Communications in OSG: 'SecureCommunicationsOSG.md'
  - Software Vulnerability Handling: 'SoftwareVulnerabilityHandling.md'
  - Joining/Leaving Security Team: 'JoiningLeavingSecurityTeam.md'
  - Incident Discovery Reporting: 'IncidentDiscoveryReporting.md'
- Integrated Security for the OSG:
  - Security Awareness for the OSG: 'SecurityAwarenessForTheOSG.md'
  - Security User Responsibilities: 'SecurityUserResponsibilities.md'
  - Security Site Responsibilities: 'SecuritySiteResponsibilities.md'

markdown_extensions:
  - admonition
  - osg_markdown.colors

